export interface IssuingAuthority {
  issuerId: number;
  jurisdiction: string;
  abbr: string | null;
  country: "Canada" | "USA" | "Mexico";
}

export const ISSUING_AUTHORITIES: IssuingAuthority[] = [
  {
    issuerId: 604426,
    jurisdiction: "Prince Edward Island",
    abbr: "PE",
    country: "Canada",
  },
  {
    issuerId: 604427,
    jurisdiction: "American Samoa",
    abbr: "AS",
    country: "USA",
  },
  {
    issuerId: 604428,
    jurisdiction: "Quebec",
    abbr: "QC",
    country: "Canada",
  },
  {
    issuerId: 604429,
    jurisdiction: "Yukon",
    abbr: "YT",
    country: "Canada",
  },
  {
    issuerId: 604430,
    jurisdiction: "Norther Marianna Islands",
    abbr: "MP",
    country: "USA",
  },
  {
    issuerId: 604431,
    jurisdiction: "Puerto Rico",
    abbr: "PR",
    country: "USA",
  },
  {
    issuerId: 604432,
    jurisdiction: "Alberta",
    abbr: "AB",
    country: "Canada",
  },
  {
    issuerId: 604433,
    jurisdiction: "Nunavut",
    abbr: "NU",
    country: "Canada",
  },
  {
    issuerId: 604434,
    jurisdiction: "Northwest Territories",
    abbr: "NT",
    country: "Canada",
  },
  {
    issuerId: 636000,
    jurisdiction: "Virginia",
    abbr: "VA",
    country: "USA",
  },
  {
    issuerId: 636001,
    jurisdiction: "New York",
    abbr: "NY",
    country: "USA",
  },
  {
    issuerId: 636002,
    jurisdiction: "Massachusetts",
    abbr: "MA",
    country: "USA",
  },
  {
    issuerId: 636003,
    jurisdiction: "Maryland",
    abbr: "MD",
    country: "USA",
  },
  {
    issuerId: 636004,
    jurisdiction: "North Carolina",
    abbr: "NC",
    country: "USA",
  },
  {
    issuerId: 636005,
    jurisdiction: "South Carolina",
    abbr: "SC",
    country: "USA",
  },
  {
    issuerId: 636006,
    jurisdiction: "Connecticut",
    abbr: "CT",
    country: "USA",
  },
  {
    issuerId: 636007,
    jurisdiction: "Louisiana",
    abbr: "LA",
    country: "USA",
  },
  {
    issuerId: 636008,
    jurisdiction: "Montana",
    abbr: "MT",
    country: "USA",
  },
  {
    issuerId: 636009,
    jurisdiction: "New Mexico",
    abbr: "NM",
    country: "USA",
  },
  {
    issuerId: 636010,
    jurisdiction: "Florida",
    abbr: "FL",
    country: "USA",
  },
  {
    issuerId: 636011,
    jurisdiction: "Delaware",
    abbr: "DE",
    country: "USA",
  },
  {
    issuerId: 636012,
    jurisdiction: "Ontario",
    abbr: "ON",
    country: "Canada",
  },
  {
    issuerId: 636013,
    jurisdiction: "Nova Scotia",
    abbr: "NS",
    country: "Canada",
  },
  {
    issuerId: 636014,
    jurisdiction: "California",
    abbr: "CA",
    country: "USA",
  },
  {
    issuerId: 636015,
    jurisdiction: "Texas",
    abbr: "TX",
    country: "USA",
  },
  {
    issuerId: 636016,
    jurisdiction: "Newfoundland",
    abbr: "NF",
    country: "Canada",
  },
  {
    issuerId: 636017,
    jurisdiction: "New Brunswick",
    abbr: "NB",
    country: "Canada",
  },
  {
    issuerId: 636018,
    jurisdiction: "Iowa",
    abbr: "IA",
    country: "USA",
  },
  {
    issuerId: 636019,
    jurisdiction: "Guam",
    abbr: "GU",
    country: "USA",
  },
  {
    issuerId: 636020,
    jurisdiction: "Colorado",
    abbr: "GM",
    country: "USA",
  },
  {
    issuerId: 636021,
    jurisdiction: "Arkansas",
    abbr: "AR",
    country: "USA",
  },
  {
    issuerId: 636022,
    jurisdiction: "Kansas",
    abbr: "KS",
    country: "USA",
  },
  {
    issuerId: 636023,
    jurisdiction: "Ohio",
    abbr: "OH",
    country: "USA",
  },
  {
    issuerId: 636024,
    jurisdiction: "Vermont",
    abbr: "VT",
    country: "USA",
  },
  {
    issuerId: 636025,
    jurisdiction: "Pennsylvania",
    abbr: "PA",
    country: "USA",
  },
  {
    issuerId: 636026,
    jurisdiction: "Arizona",
    abbr: "AZ",
    country: "USA",
  },
  {
    issuerId: 636027,
    jurisdiction: "State Dept. (Diplomatic)",
    abbr: null,
    country: "USA",
  },
  {
    issuerId: 636028,
    jurisdiction: "British Columbia",
    abbr: "BC",
    country: "Canada",
  },
  {
    issuerId: 636029,
    jurisdiction: "Oregon",
    abbr: "OR",
    country: "USA",
  },
  {
    issuerId: 636030,
    jurisdiction: "Missouri",
    abbr: "MO",
    country: "USA",
  },
  {
    issuerId: 636031,
    jurisdiction: "Wisconsin",
    abbr: "WI",
    country: "USA",
  },
  {
    issuerId: 636032,
    jurisdiction: "Michigan",
    abbr: "MI",
    country: "USA",
  },
  {
    issuerId: 636033,
    jurisdiction: "Alabama",
    abbr: "AL",
    country: "USA",
  },
  {
    issuerId: 636034,
    jurisdiction: "North Dakota",
    abbr: "ND",
    country: "USA",
  },
  {
    issuerId: 636035,
    jurisdiction: "Illinois",
    abbr: "IL",
    country: "USA",
  },
  {
    issuerId: 636036,
    jurisdiction: "New Jersey",
    abbr: "NJ",
    country: "USA",
  },
  {
    issuerId: 636037,
    jurisdiction: "Indiana",
    abbr: "IN",
    country: "USA",
  },
  {
    issuerId: 636038,
    jurisdiction: "Minnesota",
    abbr: "MN",
    country: "USA",
  },
  {
    issuerId: 636039,
    jurisdiction: "New Hampshire",
    abbr: "NH",
    country: "USA",
  },
  {
    issuerId: 636040,
    jurisdiction: "Utah",
    abbr: "UT",
    country: "USA",
  },
  {
    issuerId: 636041,
    jurisdiction: "Maine",
    abbr: "ME",
    country: "USA",
  },
  {
    issuerId: 636042,
    jurisdiction: "South Dakota",
    abbr: "SD",
    country: "USA",
  },
  {
    issuerId: 636043,
    jurisdiction: "District of Columbia",
    abbr: "DC",
    country: "USA",
  },
  {
    issuerId: 636044,
    jurisdiction: "Saskatchewan",
    abbr: "SK",
    country: "Canada",
  },
  {
    issuerId: 636045,
    jurisdiction: "Washington",
    abbr: "WA",
    country: "USA",
  },
  {
    issuerId: 636046,
    jurisdiction: "Kentucky",
    abbr: "KY",
    country: "USA",
  },
  {
    issuerId: 636047,
    jurisdiction: "Hawaii",
    abbr: "HI",
    country: "USA",
  },
  {
    issuerId: 636048,
    jurisdiction: "Manitoba",
    abbr: "MB",
    country: "Canada",
  },
  {
    issuerId: 636049,
    jurisdiction: "Nevada",
    abbr: "NV",
    country: "USA",
  },
  {
    issuerId: 636050,
    jurisdiction: "Idaho",
    abbr: "ID",
    country: "USA",
  },
  {
    issuerId: 636051,
    jurisdiction: "Mississippi",
    abbr: "MS",
    country: "USA",
  },
  {
    issuerId: 636052,
    jurisdiction: "Rhode Island",
    abbr: "RI",
    country: "USA",
  },
  {
    issuerId: 636053,
    jurisdiction: "Tennessee",
    abbr: "TN",
    country: "USA",
  },
  {
    issuerId: 636054,
    jurisdiction: "Nebraska",
    abbr: "NE",
    country: "USA",
  },
  {
    issuerId: 636055,
    jurisdiction: "Georgia",
    abbr: "GA",
    country: "USA",
  },
  {
    issuerId: 636056,
    jurisdiction: "Coahuila",
    abbr: "CU",
    country: "Mexico",
  },
  {
    issuerId: 636057,
    jurisdiction: "Hidalgo",
    abbr: "HL",
    country: "Mexico",
  },
  {
    issuerId: 636058,
    jurisdiction: "Oklahoma",
    abbr: "OK",
    country: "USA",
  },
  {
    issuerId: 636059,
    jurisdiction: "Alaska",
    abbr: "AK",
    country: "USA",
  },
  {
    issuerId: 636060,
    jurisdiction: "Wyoming",
    abbr: "WY",
    country: "USA",
  },
  {
    issuerId: 636061,
    jurisdiction: "West Virginia",
    abbr: "WV",
    country: "USA",
  },
  {
    issuerId: 636062,
    jurisdiction: "Virgin Islands",
    abbr: "VI",
    country: "USA",
  },
];

export function getAuthorityById(
  issuerId: number,
): IssuingAuthority | undefined {
  return ISSUING_AUTHORITIES.filter(
    (authority) => authority.issuerId === issuerId,
  )[0];
}
